2024-02-26 16:57:21,990 INFO    MainThread:21959 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-26 16:57:21,991 INFO    MainThread:21959 [wandb_setup.py:_flush():76] Configure stats pid to 21959
2024-02-26 16:57:21,991 INFO    MainThread:21959 [wandb_setup.py:_flush():76] Loading settings from /home/featurize/.config/wandb/settings
2024-02-26 16:57:21,991 INFO    MainThread:21959 [wandb_setup.py:_flush():76] Loading settings from /home/featurize/wandb/settings
2024-02-26 16:57:21,991 INFO    MainThread:21959 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-26 16:57:21,991 INFO    MainThread:21959 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-26 16:57:21,991 INFO    MainThread:21959 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-26 16:57:21,991 ERROR   MainThread:21959 [wandb_setup.py:_flush():76] error
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.10/site-packages/click/termui.py", line 129, in prompt_func
    return f("")
  File "/environment/miniconda3/lib/python3.10/site-packages/click/termui.py", line 54, in hidden_prompt_func
    return getpass.getpass(prompt)
  File "/environment/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 1185, in getpass
    return self._input_request(
  File "/environment/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 1245, in _input_request
    raise KeyboardInterrupt(msg) from None
KeyboardInterrupt: Interrupted by user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1172, in init
    wi.setup(kwargs)
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 306, in setup
    wandb_login._login(
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 317, in _login
    wlogin.prompt_api_key()
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 240, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 220, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/apikey.py", line 151, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/environment/miniconda3/lib/python3.10/site-packages/click/termui.py", line 147, in prompt
    value = prompt_func(prompt)
  File "/environment/miniconda3/lib/python3.10/site-packages/click/termui.py", line 136, in prompt_func
    raise Abort()
click.exceptions.Abort
2024-02-26 16:57:21,992 ERROR   MainThread:21959 [wandb_setup.py:_flush():76] error
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.10/site-packages/click/termui.py", line 129, in prompt_func
    return f("")
  File "/environment/miniconda3/lib/python3.10/site-packages/click/termui.py", line 54, in hidden_prompt_func
    return getpass.getpass(prompt)
  File "/environment/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 1185, in getpass
    return self._input_request(
  File "/environment/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 1245, in _input_request
    raise KeyboardInterrupt(msg) from None
KeyboardInterrupt: Interrupted by user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1172, in init
    wi.setup(kwargs)
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 306, in setup
    wandb_login._login(
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 317, in _login
    wlogin.prompt_api_key()
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 240, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 220, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/environment/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/apikey.py", line 151, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/environment/miniconda3/lib/python3.10/site-packages/click/termui.py", line 147, in prompt
    value = prompt_func(prompt)
  File "/environment/miniconda3/lib/python3.10/site-packages/click/termui.py", line 136, in prompt_func
    raise Abort()
click.exceptions.Abort
2024-02-26 16:57:21,992 INFO    MainThread:21959 [wandb_init.py:_log_setup():526] Logging user logs to /home/featurize/wandb/run-20240226_165721-n415gyvo/logs/debug.log
2024-02-26 16:57:21,992 INFO    MainThread:21959 [wandb_init.py:_log_setup():527] Logging internal logs to /home/featurize/wandb/run-20240226_165721-n415gyvo/logs/debug-internal.log
2024-02-26 16:57:21,993 INFO    MainThread:21959 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f33334c4f70>
2024-02-26 16:57:21,993 INFO    MainThread:21959 [wandb_init.py:init():566] calling init triggers
2024-02-26 16:57:21,993 INFO    MainThread:21959 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-26 16:57:21,993 INFO    MainThread:21959 [wandb_init.py:init():616] starting backend
2024-02-26 16:57:21,993 INFO    MainThread:21959 [wandb_init.py:init():620] setting up manager
2024-02-26 16:57:21,994 INFO    MainThread:21959 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-26 16:57:21,996 INFO    MainThread:21959 [wandb_init.py:init():628] backend started and connected
2024-02-26 16:57:21,998 INFO    MainThread:21959 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-26 16:57:21,999 INFO    MainThread:21959 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-26 16:57:21,999 INFO    MainThread:21959 [wandb_init.py:init():720] updated telemetry
2024-02-26 16:57:22,002 INFO    MainThread:21959 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-26 16:57:22,706 INFO    MainThread:21959 [wandb_run.py:_on_init():2262] communicating current version
2024-02-26 16:57:22,986 INFO    MainThread:21959 [wandb_run.py:_on_init():2271] got version response 
2024-02-26 16:57:22,987 INFO    MainThread:21959 [wandb_init.py:init():804] starting run threads in backend
2024-02-26 16:57:31,600 INFO    MainThread:21959 [wandb_run.py:_console_start():2241] atexit reg
2024-02-26 16:57:31,601 INFO    MainThread:21959 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-26 16:57:31,602 INFO    MainThread:21959 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-26 16:57:31,602 INFO    MainThread:21959 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-26 16:57:31,604 INFO    MainThread:21959 [wandb_init.py:init():847] run started, returning control to user process
2024-02-26 16:57:31,608 INFO    MainThread:21959 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-26 16:57:31,608 INFO    MainThread:21959 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-26 17:00:46,618 INFO    MainThread:21959 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-26 17:04:30,400 INFO    MainThread:21959 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-26 17:04:30,400 INFO    MainThread:21959 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-26 17:04:42,254 INFO    MainThread:21959 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-26 17:04:42,313 INFO    MainThread:21959 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-26 17:04:42,313 INFO    MainThread:21959 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-26 17:04:44,293 INFO    MainThread:21959 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-26 17:04:46,173 INFO    MainThread:21959 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-26 17:04:46,174 INFO    MainThread:21959 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-26 17:27:38,372 INFO    MainThread:21959 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-26 17:31:08,375 INFO    MainThread:21959 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-26 17:31:08,375 INFO    MainThread:21959 [wandb_init.py:_pause_backend():437] pausing backend
